version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: voxar
      POSTGRES_PASSWORD: voxarpassword
      POSTGRES_DB: voxarhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    # Usamos o pipenv para rodar o servidor
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://voxar:voxarpassword@db:5432/voxarhub
      # O compose vai ler a chave do seu arquivo .env local
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

volumes:
  postgres_data: